# Generated by Django 4.2.1 on 2023-06-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=120)),
                ('member_name', models.CharField(max_length=120)),
                ('client_name', models.CharField(max_length=120)),
                ('finished_date', models.DateTimeField()),
                ('project_photo', models.ImageField(upload_to='projects-photos/')),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.section')),
                ('skills', models.ManyToManyField(to='team.skill')),
            ],
        ),
    ]
